import SwiftUI
import Combine

enum AppLanguage: String, CaseIterable, Identifiable {
    case turkish = "tr"
    case english = "en"
    case german = "de"
    
    var id: String { rawValue }
    
    var displayName: String {
        switch self {
        case .turkish: return "Türkçe"
        case .english: return "English"
        case .german: return "Deutsch"
        }
    }
    
    var code: String {
        switch self {
        case .turkish: return "TR"
        case .english: return "EN"
        case .german: return "DE"
        }
    }
}

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    
    @Published var currentLanguage: AppLanguage = .turkish
    
    private let translations: [String: [AppLanguage: String]] = [
        "tc_manual": [.turkish: "Kullanma Kılavuzu", .english: "User Manual", .german: "Bedienungsanleitung"],
        "tc_searching_connection": [.turkish: "Bağlantı Aranıyor...", .english: "Searching Connection...", .german: "Verbindung wird gesucht..."],
        "manual_subtitle": [.turkish: "INCA IKG-455 Donanımsal Kısayollar ve Kontrol Rehberi", .english: "INCA IKG-455 Hardware Shortcuts & Control Guide", .german: "INCA IKG-455 Hardware-Kurzbefehle & Steuerungsleitfaden"],
        "manual_knob_header": [.turkish: "DÖNER TEKERLEK (KNOB) ÇALIŞMA MANTIĞI", .english: "ROTARY KNOB WORKING PRINCIPLE", .german: "DREHKNOPF-FUNKTIONSPRINZIP"],
        "manual_knob_badge": [.turkish: "Donanımsal Geçiş", .english: "Hardware Switch", .german: "Hardware-Umschaltung"],
        "manual_knob_hold_combo": [.turkish: "3-5 Saniye Basılı Tutun", .english: "Hold for 3-5 Seconds", .german: "3-5 Sekunden gedrückt halten"],
        "manual_knob_hold_action": [.turkish: "Ses & Medya Modu ⟷ RGB Parlaklık Modu", .english: "Volume & Media Mode ⟷ RGB Brightness Mode", .german: "Lautstärke- & Medienmodus ⟷ RGB-Helligkeitsmodus"],
        "manual_knob_hold_desc": [.turkish: "Tekerleğe dik şekilde 3-5 saniye basılı tuttuğunuzda klavye ışıkları 3 defa yanıp söner ve çalışma modunu değiştirir.", .english: "When pressed vertically for 3-5 seconds, keyboard lights blink 3 times and toggle the operating mode.", .german: "Wenn 3-5 Sekunden lang vertikal gedrückt gehalten, blinkt die Tastatur 3 Mal und wechselt den Betriebsmodus."],
        "manual_knob_click_combo": [.turkish: "Tek Tık (Kısa Basış)", .english: "Single Click", .german: "Einfacher Klick"],
        "manual_knob_click_action": [.turkish: "Sesi Kapat (Mute) ya da Efekt Değiştir", .english: "Mute Audio or Cycle Effect", .german: "Stummschalten oder Effekt wechseln"],
        "manual_knob_click_desc": [.turkish: "Ses modundayken sesi tamamen susturur/açar. Işık modundayken ana aydınlatma efektini bir sonraki moda atlatır.", .english: "In volume mode, mutes/unmutes audio. In lighting mode, switches to the next lighting effect.", .german: "Im Lautstärkemodus stumm/laut. Im Lichtmodus nächster Beleuchtungseffekt."],
        "manual_knob_turn_combo": [.turkish: "Sağa / Sola Çevirme", .english: "Rotate Left / Right", .german: "Nach links / rechts drehen"],
        "manual_knob_turn_action": [.turkish: "Ses Seviyesi ya da Işık Parlaklığı", .english: "Volume Level or Light Brightness", .german: "Lautstärke oder Helligkeit"],
        "manual_knob_turn_desc": [.turkish: "Ses modunda sistem sesini artırıp azaltır; ışık modunda klavye aydınlatmasının parlaklık kademesini ayarlar.", .english: "In volume mode, adjusts system volume; in lighting mode, adjusts backlight brightness levels.", .german: "Im Lautstärkemodus Systemlautstärke regeln; im Lichtmodus Helligkeitsstufen anpassen."],
        "manual_system_header": [.turkish: "SİSTEM & SIFIRLAMA", .english: "SYSTEM & RESET", .german: "SYSTEM & ZURÜCKSETZEN"],
        "manual_fn_esc_action": [.turkish: "Fabrika Ayarlarına Sıfırlama", .english: "Factory Reset", .german: "Werkseinstellungen"],
        "manual_fn_esc_desc": [.turkish: "Klavyeyi ilk fabrika ayarlarına sıfırlar ve dahili hafızayı yeniler.", .english: "Resets keyboard to initial factory defaults and refreshes internal memory.", .german: "Setzt die Tastatur auf Werkseinstellungen zurück."],
        "manual_fn_a_action": [.turkish: "macOS Modu (Mac Layout)", .english: "macOS Mode (Mac Layout)", .german: "macOS-Modus (Mac-Layout)"],
        "manual_fn_a_desc": [.turkish: "Klavyeyi macOS tuş düzenine geçirir (Command ⌘ ve Option ⌥ düzeni aktif olur).", .english: "Switches keyboard to macOS layout (Command ⌘ and Option ⌥ key order).", .german: "Schaltet Tastatur auf macOS-Layout um (Command ⌘ und Option ⌥)."],
        "manual_fn_w_action": [.turkish: "Windows Modu (Win Layout)", .english: "Windows Mode (Win Layout)", .german: "Windows-Modus (Win-Layout)"],
        "manual_fn_w_desc": [.turkish: "Klavyeyi standart Windows/PC tuş dizilimine geri alır.", .english: "Restores keyboard to standard Windows/PC key layout.", .german: "Stellt die Standard-Windows/PC-Tastenbelegung wieder her."],
        "manual_rgb_header": [.turkish: "RGB AYDINLATMA KONTROLLERİ", .english: "RGB LIGHTING CONTROLS", .german: "RGB-BELEUCHTUNGSSTEUERUNG"],
        "manual_fn_slash_action": [.turkish: "Arka Aydınlatma Efekti", .english: "Backlight Effect", .german: "Hintergrundbeleuchtungseffekt"],
        "manual_fn_slash_desc": [.turkish: "Dahili RGB efektleri arasında sırayla geçiş yapar.", .english: "Cycles sequentially through built-in RGB effects.", .german: "Wechselt nacheinander durch integrierte RGB-Effekte."],
        "manual_fn_space_action": [.turkish: "Işıkları Kapat / Aç", .english: "Toggle Lights On / Off", .german: "Lichter Ein- / Ausschalten"],
        "manual_fn_space_desc": [.turkish: "Klavyenin tüm arka aydınlatmasını anında kapatır ya da tekrar açar.", .english: "Instantly toggles entire keyboard backlight on or off.", .german: "Schaltet die gesamte Tastaturbeleuchtung sofort ein oder aus."],
        "manual_fn_up_action": [.turkish: "Parlaklık Artır (+)", .english: "Brightness Up (+)", .german: "Helligkeit erhöhen (+)"],
        "manual_fn_up_desc": [.turkish: "Arka aydınlatmanın parlaklık kademesini artırır.", .english: "Increases backlight brightness level.", .german: "Erhöht die Helligkeitsstufe der Hintergrundbeleuchtung."],
        "manual_fn_down_action": [.turkish: "Parlaklık Azalt (-)", .english: "Brightness Down (-)", .german: "Helligkeit verringern (-)"],
        "manual_fn_down_desc": [.turkish: "Arka aydınlatmanın parlaklık kademesini kısar.", .english: "Decreases backlight brightness level.", .german: "Verringert die Helligkeitsstufe der Hintergrundbeleuchtung."],
        "manual_fn_right_action": [.turkish: "Efekt Hızı Artır (+)", .english: "Effect Speed Up (+)", .german: "Effektgeschwindigkeit erhöhen (+)"],
        "manual_fn_right_desc": [.turkish: "Animasyon ve dalga efektlerinin akış hızını artırır.", .english: "Increases animation and wave flow speed.", .german: "Erhöht die Animations- und Wellengeschwindigkeit."],
        "manual_fn_left_action": [.turkish: "Efekt Hızı Azalt (-)", .english: "Effect Speed Down (-)", .german: "Effektgeschwindigkeit verringern (-)"],
        "manual_fn_left_desc": [.turkish: "Animasyon ve dalga efektlerinin akış hızını yavaşlatır.", .english: "Slows down animation and wave flow speed.", .german: "Verlangsamt die Animations- und Wellengeschwindigkeit."],
        "manual_fn_enter_action": [.turkish: "Yan Şerit (Side LED)", .english: "Side Strip (Side LED)", .german: "Seitenstreifen (Side LED)"],
        "manual_fn_enter_desc": [.turkish: "Klavyenin yan gövdesindeki RGB şeritlerinin modlarını değiştirir.", .english: "Changes modes of the RGB strips along the keyboard sides.", .german: "Wechselt die Modi der seitlichen RGB-Streifen."],
        "manual_conn_header": [.turkish: "BAĞLANTI MODLARI & EŞLEŞTİRME", .english: "CONNECTION MODES & PAIRING", .german: "VERBINDUNGSMODI & KOPPLUNG"],
        "manual_fn_123_action": [.turkish: "Bluetooth 5.0 (Cihaz 1, 2, 3)", .english: "Bluetooth 5.0 (Device 1, 2, 3)", .german: "Bluetooth 5.0 (Gerät 1, 2, 3)"],
        "manual_fn_123_desc": [.turkish: "Kısa basış cihazlar arası geçiş yapar; 3 saniye basılı tutma Bluetooth eşleştirme modunu başlatır.", .english: "Short press switches between devices; holding 3 seconds starts Bluetooth pairing mode.", .german: "Kurzer Druck wechselt Geräte; 3 Sekunden langes Halten startet Kopplungsmodus."],
        "manual_fn_4_action": [.turkish: "2.4G Kablosuz Alıcı", .english: "2.4G Wireless Dongle", .german: "2.4G Kabelloser Empfänger"],
        "manual_fn_4_desc": [.turkish: "Klavyeyi kutudan çıkan 2.4 GHz USB kablosuz alıcı moduna geçirir.", .english: "Switches keyboard to the 2.4 GHz USB wireless dongle mode.", .german: "Schaltet Tastatur in den 2,4-GHz-USB-Dongle-Modus."],
        "manual_fn_5_action": [.turkish: "Type-C Kablolu Bağlantı", .english: "Type-C Wired Connection", .german: "Type-C Kabelgebunden"],
        "manual_fn_5_desc": [.turkish: "USB-C kablosu üzerinden en yüksek yoklama hızı (1000Hz) ile kablolu moda geçer.", .english: "Switches to wired mode over USB-C with highest polling rate (1000Hz).", .german: "Schaltet über USB-C mit höchster Abfragerate (1000Hz) in den Kabelmodus."],
        "tc_about": [.turkish: "Hakkında", .english: "About", .german: "Über"],
        "tc_charging": [.turkish: "Şarj Ediliyor", .english: "Charging", .german: "Wird geladen"],
        "tc_fully_charged": [.turkish: "Tamamen Şarj Oldu", .english: "Fully Charged", .german: "Vollständig geladen"],
        "tc_fully_charged_desc": [.turkish: "Pil tamamen doldu. Dilerseniz kablosuz kullanıma geçebilirsiniz.", .english: "Battery is completely full. You can switch to wireless mode.", .german: "Akku ist vollständig geladen. Sie können in den kabellosen Modus wechseln."],
        "tc_low_battery": [.turkish: "Batarya Zayıf", .english: "Low Battery", .german: "Niedriger Akkustand"],
        "tc_low_battery_warning": [.turkish: "Batarya seviyesi kritik derecede düşük (%@). Kesintisiz kullanım için lütfen Type-C kablosuyla şarja takın.", .english: "Battery level is critically low (%@). Please connect via Type-C cable to charge.", .german: "Akkustand ist kritisch niedrig (%@). Bitte über Type-C-Kabel aufladen."],
        "tc_on_battery": [.turkish: "Batarya Modu", .english: "On Battery", .german: "Akkubetrieb"],
        "about_version": [.turkish: "Sürüm 1.0.0 (Build 2026.1)", .english: "Version 1.0.0 (Build 2026.1)", .german: "Version 1.0.0 (Build 2026.1)"],
        "about_project_header": [.turkish: "PROJE HAKKINDA", .english: "ABOUT THE PROJECT", .german: "ÜBER DAS PROJEKT"],
        "about_project_desc": [.turkish: "INCA IKG-455 Manyetik Eksen mekanik klavye için resmi bir macOS sürücüsü veya yapılandırma yazılımı bulunmamaktadır. Bu uygulama, klavyenin RGB aydınlatma modlarını, çok katmanlı tuş atamalarını, TFT ekran animasyonlarını ve donanım telemetrisini macOS ekosisteminde verimli bir şekilde yönetebilmek amacıyla bağımsız bir hobi projesi olarak geliştirilmiştir.", .english: "There is no official macOS driver or configuration software for the INCA IKG-455 Magnetic Axis mechanical keyboard. This application was developed as an independent hobby project to efficiently manage the keyboard's RGB lighting modes, multi-layer key assignments, TFT screen animations, and hardware telemetry within the macOS ecosystem.", .german: "Für die mechanische Tastatur INCA IKG-455 Magnetic Axis gibt es keinen offiziellen macOS-Treiber oder Konfigurationssoftware. Diese Anwendung wurde als unabhängiges Hobbyprojekt entwickelt, um die RGB-Beleuchtungsmodi, mehrschichtige Tastenzuweisungen, TFT-Bildschirmanimationen und Hardware-Telemetrie im macOS-Ökosystem effizient zu verwalten."],
        "about_hig_desc": [.turkish: "Uygulama tasarımı ve kullanıcı deneyimi, Apple macOS Human Interface Guidelines (HIG) ilkelerine sadık kalınarak sade ve modern bir dille inşa edilmiştir.", .english: "Application design and user experience have been crafted following Apple macOS Human Interface Guidelines (HIG) with a clean, modern aesthetic.", .german: "Das Design und die Benutzererfahrung der Anwendung wurden nach den Richtlinien der Apple macOS Human Interface Guidelines (HIG) mit einer klaren, modernen Ästhetik gestaltet."],
        "about_dev_header": [.turkish: "GELİŞTİRİCİ VE KAYNAKLAR", .english: "DEVELOPER & RESOURCES", .german: "ENTWICKLER & RESSOURCEN"],
        "about_dev_role": [.turkish: "Açık Kaynak Geliştirici", .english: "Open Source Developer", .german: "Open-Source-Entwickler"],
        "about_target_hw": [.turkish: "Hedef Donanım", .english: "Target Hardware", .german: "Zielhardware"],
        "about_supported_protocols": [.turkish: "Desteklenen Protokoller", .english: "Supported Protocols", .german: "Unterstützte Protokolle"],
        "about_protocols_val": [.turkish: "Type-C Kablolu • 2.4G Kablosuz • Bluetooth 5.0", .english: "Type-C Wired • 2.4G Wireless • Bluetooth 5.0", .german: "Type-C Kabelgebunden • 2.4G Kabellos • Bluetooth 5.0"],
        "about_copyright": [.turkish: "© 2026 İsmailcan USLU. Tüm hakları saklıdır.", .english: "© 2026 İsmailcan USLU. All rights reserved.", .german: "© 2026 İsmailcan USLU. Alle Rechte vorbehalten."],
        "tc_PL": [.turkish: "Oynat/Durdur", .english: "Play/Pause", .german: "Wiedergabe/Pause"],
        "tc_apply": [.turkish: "Kaydet", .english: "Save", .german: "Speichern"],
        "tc_back": [.turkish: "Geri", .english: "Back", .german: "Rückwärts"],
        "tc_bridn": [.turkish: "Ekran Parlaklığı -", .english: "Screen -", .german: "Bildschirmhelligkeit -"],
        "tc_briup": [.turkish: "Ekran Parlaklığı +", .english: "Screen +", .german: "Bildschirmhelligkeit +"],
        "tc_cancel": [.turkish: "İptal", .english: "Cancel", .german: "Abbrechen"],
        "tc_click": [.turkish: "Sol Tuş", .english: "Left Button", .german: "Linke Taste"],
        "tc_cmd1": [.turkish: "Pencereyi Kapat", .english: "Close window", .german: "Fenster schließen"],
        "tc_cmd11": [.turkish: "Win Tuşunu Kilitle", .english: "Lock Win", .german: "Windows-Taste sperren"],
        "tc_cmd12": [.turkish: "Klavyeyi Kilitle", .english: "Lock Keyboard", .german: "Tastatur sperren"],
        "tc_cmd13": [.turkish: "Sıfırlama", .english: "Reset", .german: "Tastatur zurücksetzen"],
        "tc_cmd2": [.turkish: "Bilgisayarı Kilitle", .english: "Lock computer", .german: "Computer sperren"],
        "tc_cmd3": [.turkish: "Çalıştır", .english: "Run", .german: "Befehl ausführen"],
        "tc_cmd4": [.turkish: "Masaüstünü Göster", .english: "Show desktop", .german: "Desktop anzeigen"],
        "tc_cmd5": [.turkish: "Yakınlaştır", .english: "Zoom in", .german: "Vergrößern"],
        "tc_cmd6": [.turkish: "Uzaklaştır", .english: "Zoom out", .german: "Verkleinern"],
        "tc_cmd7": [.turkish: "Görev Yöneticisi", .english: "Task manager", .german: "Task-Manager"],
        "tc_cmd8": [.turkish: "Geri Al", .english: "Undo", .german: "Rückgängig machen"],
        "tc_cmd9": [.turkish: "Kaydet", .english: "Save", .german: "Speichern"],
        "tc_config": [.turkish: "Ayarlar", .english: "Config", .german: "Konfiguration"],
        "tc_dclick": [.turkish: "Çift Tıklama", .english: "Double Click", .german: "Linksklick doppelt"],
        "tc_exit": [.turkish: "Çıkış", .english: "Exit", .german: "Beenden"],
        "tc_forward": [.turkish: "İleri", .english: "Forward", .german: "Vorwärts"],
        "tc_game1": [.turkish: "FN+1", .english: "FN+1", .german: "FN+1"],
        "tc_game2": [.turkish: "FN+2", .english: "FN+2", .german: "FN+2"],
        "tc_game3": [.turkish: "FN+3", .english: "FN+3", .german: "FN+3"],
        "tc_game4": [.turkish: "FN+4", .english: "FN+4", .german: "FN+4"],
        "tc_game5": [.turkish: "FN+5", .english: "FN+5", .german: "FN+5"],
        "tc_kb1": [.turkish: "Işık Efekti", .english: "Light effect", .german: "Tastaturbeleuchtungseffekte"],
        "tc_kb10": [.turkish: "Mevcut", .english: "Current", .german: "Aktuell"],
        "tc_kb11": [.turkish: "Hiçbir Tuş Fonksiyonu Seçilmedi", .english: "No key function is selected", .german: "Keine Tastenfunktion ausgewählt"],
        "tc_kb12": [.turkish: "Hassasiyet", .english: "Sensitivity", .german: "Empfindlichkeit"],
        "tc_kb13": [.turkish: "Tuşu Sıfırla", .english: "Reset Key", .german: "Taste zurücksetzen"],
        "tc_kb14": [.turkish: "Otomatik Tespit", .english: "Automatic detection", .german: "Automatic detection"],
        "tc_kb2": [.turkish: "Lütfen Önce Bir Tuş Seçin", .english: "Please select a key first", .german: "Bitte zuerst eine Taste auswählen"],
        "tc_kb3": [.turkish: "Renk Grubu", .english: "Color group", .german: "Farbgruppe"],
        "tc_kb4": [.turkish: "Birden Fazla Tuş Seçmek için Sol Tuşu Tutup Fareyi Hareket Ettirin", .english: "Press and hold the left button to move the mouse to select multiple keys", .german: "Halten Sie die linke Maustaste gedrückt und bewegen Sie sie, um mehrere Tasten auszuwählen"],
        "tc_kb5": [.turkish: "Varsayılan", .english: "Default", .german: "Standardtastenschicht"],
        "tc_kb6": [.turkish: "FN1", .english: "FN1", .german: "FN1-Schicht"],
        "tc_kb7": [.turkish: "FN2", .english: "FN2", .german: "FN2-Schicht"],
        "tc_kb8": [.turkish: "Dokun", .english: "Tap", .german: "Tippen"],
        "tc_kb9": [.turkish: "Varsayılan", .english: "Default", .german: "Standard"],
        "tc_kb_led1": [.turkish: "Sabit Açık", .english: "Fixed_on", .german: "Immer_an"],
        "tc_kb_led10": [.turkish: "Retro Yılan", .english: "Retro_snake", .german: "Retro_Schlange"],
        "tc_kb_led11": [.turkish: "Neon Akışı", .english: "Neon_stream", .german: "Neonstrom"],
        "tc_kb_led12": [.turkish: "Reaksiyon Efekti", .english: "Reaction", .german: "Reaktion"],
        "tc_kb_led13": [.turkish: "Sinüs Dalga", .english: "Sine_wave", .german: "Sinuswelle"],
        "tc_kb_led14": [.turkish: "Takip Eden Tarama", .english: "Retinue scanning", .german: "Begleiter-Scan"],
        "tc_kb_led15": [.turkish: "Dönen Venüs", .english: "Rotating windmill", .german: "Drehendes_Windrad"],
        "tc_kb_led16": [.turkish: "Renkli Şelale", .english: "Colorful waterfall", .german: "Bunter_Wasserfall"],
        "tc_kb_led17": [.turkish: "Çiçek Açma", .english: "Blossoming", .german: "Blühen"],
        "tc_kb_led18": [.turkish: "Dönen Fırtına", .english: "Rotating storm", .german: "Drehender_Sturm"],
        "tc_kb_led19": [.turkish: "Kendi Ayarlaması", .english: "Self-define", .german: "Selbstdefiniert"],
        "tc_kb_led2": [.turkish: "Nefes Alma Efekti", .english: "Respire", .german: "Atmen"],
        "tc_kb_led20": [.turkish: "KAPALI", .english: "OFF", .german: "AUS"],
        "tc_kb_led3": [.turkish: "Gökkuşağı", .english: "Rainbow", .german: "Regenbogen"],
        "tc_kb_led4": [.turkish: "Uzaklaştan Parlama", .english: "Flash_away", .german: "Weit_blinken"],
        "tc_kb_led5": [.turkish: "Yağmur Damlaları", .english: "Raindrops", .german: "Regentropfen"],
        "tc_kb_led6": [.turkish: "Gökkuşağı Tekerleği", .english: "Rainbow_wheel", .german: "Regenbogenrad"],
        "tc_kb_led7": [.turkish: "Dalgalı Parıltı", .english: "Ripples_shining", .german: "Leuchtende_Wellen"],
        "tc_kb_led8": [.turkish: "Yıldızlar Parlar", .english: "Stars_twinkle", .german: "Zwinkernede_Sterne"],
        "tc_kb_led9": [.turkish: "Gölge Kaybolur", .english: "Shadow_disappear", .german: "Schatten_verschwinden"],
        "tc_kbmedia_cal": [.turkish: "Hesap Makinesi", .english: "Calculator", .german: "Rechner"],
        "tc_kbmedia_explore": [.turkish: "Bilgisayarım", .english: "My computer", .german: "Mein Computer"],
        "tc_kbmedia_favor": [.turkish: "Favoriler", .english: "Favorites", .german: "Lesezeichen"],
        "tc_kbmedia_mail": [.turkish: "E-posta", .english: "Email", .german: "E-Mail"],
        "tc_kbmedia_main": [.turkish: "Ana Sayfa", .english: "Home page", .german: "Browser"],
        "tc_kbmedia_msel": [.turkish: "Medya Çalar", .english: "Media Player", .german: "Medienplayer"],
        "tc_key_off": [.turkish: "Devre Dışı Bırak", .english: "Disable", .german: "Keine Funktion"],
        "tc_mac_def": [.turkish: "Makro", .english: "Macro", .german: "Makro"],
        "tc_macro_msg1": [.turkish: "Yeni Klasör", .english: "New folder", .german: "Neuen Ordner erstellen"],
        "tc_macro_msg10": [.turkish: "Başlat", .english: "Start", .german: "Startzeit"],
        "tc_macro_msg11": [.turkish: "Tutma Süresi", .english: "Holding time", .german: "Dauer"],
        "tc_macro_msg12": [.turkish: "Bitiş", .english: "End", .german: "Endzeit"],
        "tc_macro_msg13": [.turkish: "Görünüm Ölçeği", .english: "View scale", .german: "Ansichtsmaßstab"],
        "tc_macro_msg14": [.turkish: "Ön İzleme", .english: "Preview", .german: "Vorschau"],
        "tc_macro_msg15": [.turkish: "Şu anda makro bulunmamaktadır. Oluşturmak için tıklayın", .english: "There are currently no macros. Click to create", .german: "Es sind derzeit keine Makros vorhanden, klicken Sie, um zu erstellen"],
        "tc_macro_msg16": [.turkish: "Ekle", .english: "Insert", .german: "Ausführungsanzahl"],
        "tc_macro_msg17": [.turkish: "Döngü Sayısı", .english: "Cycle times", .german: "Execution Count"],
        "tc_macro_msg18": [.turkish: "Tuş Serbest Bırakılana Kadar Döngü", .english: "Cycle until the key released", .german: "Schleife bis Tastenfreigab"],
        "tc_macro_msg19": [.turkish: "Herhangi Bir Tuşa Basılana Kadar Döngü", .english: "Cycle until any key pressed", .german: "Schleife bis eine beliebige Taste gedrückt wird"],
        "tc_macro_msg2": [.turkish: "Yeni Makro", .english: "New macro", .german: "Neue Makro erstellen"],
        "tc_macro_msg20": [.turkish: "X Hareketi", .english: "X Move", .german: "Horizontale Bewegung"],
        "tc_macro_msg21": [.turkish: "Y Hareketi", .english: "Y Move", .german: "Vertikale Bewegung"],
        "tc_macro_msg22": [.turkish: "Gecikme", .english: "Delay", .german: "Dann warten"],
        "tc_macro_msg23": [.turkish: "Öğeyi Değiştirmek için Çift Tıklayın", .english: "Double click to modify the item", .german: "Doppelklicken, um das Projekt zu ändern"],
        "tc_macro_msg24": [.turkish: "Aynı Başlangıç Zamanı Algılandı", .english: "The same start time is detected", .german: "Die gleiche Startzeit wird erkannt"],
        "tc_macro_msg25": [.turkish: "Yeni Alt Klasör", .english: "New subfolder", .german: "New subfolder"],
        "tc_macro_msg3": [.turkish: "Lütfen bir isim girin", .english: "Please enter a name", .german: "Bitte Namen eingeben"],
        "tc_macro_msg4": [.turkish: "Kayıt Et", .english: "Record", .german: "Aufnahme starten"],
        "tc_macro_msg5": [.turkish: "Durdur", .english: "Stop", .german: "Aufnahme stoppen"],
        "tc_macro_msg6": [.turkish: "Sil", .english: "Delete", .german: "Löschen"],
        "tc_macro_msg7": [.turkish: "Tuş", .english: "Key", .german: "Taste"],
        "tc_macro_msg8": [.turkish: "Düzenle", .english: "Edit", .german: "Makro bearbeiten"],
        "tc_macro_msg9": [.turkish: "Makro Düzenleme Paneli", .english: "Macro edit panel", .german: "Makro-Bearbeitungsdialog"],
        "tc_menu": [.turkish: "Sağ Tuş", .english: "Right Button", .german: "Rechte Taste"],
        "tc_middle": [.turkish: "Orta Tuş", .english: "Middle Button", .german: "Mittlere Taste"],
        "tc_ms1": [.turkish: "DPI Stages", .english: "DPI Stages", .german: "DPI Stages"],
        "tc_ms10": [.turkish: "Loop ( 0-255 )", .english: "Loop ( 0-255 )", .german: "Loop ( 0-255 )"],
        "tc_ms11": [.turkish: "Intervals ( 5-255 )", .english: "Intervals ( 5-255 )", .german: "Intervals ( 5-255 )"],
        "tc_ms12": [.turkish: "Note：The smaller intervals value is, the faster speed of keystroke is.", .english: "Note：The smaller intervals value is, the faster speed of keystroke is.", .german: "Note：The smaller intervals value is, the faster speed of keystroke is."],
        "tc_ms13": [.turkish: "Polling Rate", .english: "Polling Rate", .german: "Polling Rate"],
        "tc_ms14": [.turkish: "XY Independent", .english: "XY Independent", .german: "XY Independent"],
        "tc_ms15": [.turkish: "At least one button must be configured as \"click\"", .english: "At least one button must be configured as \"click\"", .german: "At least one button must be configured as \"click\""],
        "tc_ms16": [.turkish: "Lighting", .english: "Lighting", .german: "Lighting"],
        "tc_ms17": [.turkish: "Direction", .english: "Direction", .german: "Direction"],
        "tc_ms18": [.turkish: "Mouse Sensitivity", .english: "Mouse Sensitivity", .german: "Mouse Sensitivity"],
        "tc_ms19": [.turkish: "Improve pointer precision", .english: "Improve pointer precision", .german: "Improve pointer precision"],
        "tc_ms2": [.turkish: "DPI Lock", .english: "DPI Lock", .german: "DPI Lock"],
        "tc_ms20": [.turkish: "Scrolling Speed", .english: "Scrolling Speed", .german: "Scrolling Speed"],
        "tc_ms21": [.turkish: "Scroll One Page", .english: "Scroll One Page", .german: "Scroll One Page"],
        "tc_ms22": [.turkish: "Double-Click Speed", .english: "Double-Click Speed", .german: "Double-Click Speed"],
        "tc_ms23": [.turkish: "Notify", .english: "Notify", .german: "Zittern."],
        "tc_ms24": [.turkish: "Display notifications when switching DPI", .english: "Display notifications when switching DPI", .german: "Display notifications when switching DPI"],
        "tc_ms3": [.turkish: "Triple Click", .english: "Triple Click", .german: "Triple Click"],
        "tc_ms4": [.turkish: "Lighting ON/OFF", .english: "Lighting ON/OFF", .german: "Lighting ON/OFF"],
        "tc_ms5": [.turkish: "Switch Effect", .english: "Switch Effect", .german: "Switch Effect"],
        "tc_ms6": [.turkish: "Switch Polling Rate", .english: "Switch Polling Rate", .german: "Switch Polling Rate"],
        "tc_ms7": [.turkish: "Switch Mode", .english: "Switch Mode", .german: "Switch Mode"],
        "tc_ms8": [.turkish: "DPI Loop", .english: "DPI Loop", .german: "DPI Loop"],
        "tc_ms9": [.turkish: "Fire key", .english: "Fire key", .german: "Fire key"],
        "tc_ms_led1": [.turkish: "Colorful Streaming", .english: "Colorful Streaming", .german: "Colorful Streaming"],
        "tc_ms_led10": [.turkish: "LED OFF", .english: "LED OFF", .german: "LED OFF"],
        "tc_ms_led2": [.turkish: "Steady", .english: "Steady", .german: "Steady"],
        "tc_ms_led3": [.turkish: "Breathing", .english: "Breathing", .german: "Breathing"],
        "tc_ms_led4": [.turkish: "Colorful Tail", .english: "Colorful Tail", .german: "Colorful Tail"],
        "tc_ms_led5": [.turkish: "Neon", .english: "Neon", .german: "Neon"],
        "tc_ms_led6": [.turkish: "Colorful Steady", .english: "Colorful Steady", .german: "Colorful Steady"],
        "tc_ms_led7": [.turkish: "Flicker", .english: "Flicker", .german: "Flicker"],
        "tc_ms_led8": [.turkish: "Stars twinkle", .english: "Stars twinkle", .german: "Stars twinkle"],
        "tc_ms_led9": [.turkish: "Wave", .english: "Wave", .german: "Wave"],
        "tc_msg1": [.turkish: "Kapsamlı", .english: "Global", .german: "Globale Einstellungen"],
        "tc_msg10": [.turkish: "Dil", .english: "Language", .german: "Sprache"],
        "tc_msg11": [.turkish: "Otomatik Çalıştırma", .english: "Autorun", .german: "Automatischer Start beim Booten"],
        "tc_msg12": [.turkish: "ACİK", .english: "ON", .german: "Ein"],
        "tc_msg13": [.turkish: "KAPALI", .english: "OFF", .german: "Aus"],
        "tc_msg14": [.turkish: "Özelleştirilmiş Renk", .english: "Custom color", .german: "Farben anpassen"],
        "tc_msg15": [.turkish: "Ekle", .english: "Add", .german: "Hinzufügen"],
        "tc_msg16": [.turkish: "Gerçekten Silmek İstiyor Musunuz？", .english: "Are you sure you want to delete？", .german: "Sind Sie sicher, dass Sie löschen möchten?"],
        "tc_msg17": [.turkish: "Gerçekten Sıfırlamak İstiyor Musunuz？", .english: "Are you sure you want to restore？", .german: "Sind Sie sicher, dass Sie auf die Werkseinstellungen zurücksetzen möchten?"],
        "tc_msg18": [.turkish: "Tuş Ataması", .english: "Key assignment", .german: "Tastenzuweisung"],
        "tc_msg19": [.turkish: "Makro Sayısı Maksimuma Ulaştı", .english: "The number of macros has reached the maximum", .german: "Maximale Anzahl von Makros erreicht"],
        "tc_msg2": [.turkish: "Cihaz Modeli", .english: "Device model", .german: "Gerätemodell"],
        "tc_msg20": [.turkish: "Otomatik Olarak Güncellemeleri Kontrol Et", .english: "Automatically check for updates", .german: "Automatische Überprüfung auf Aktualisierungen"],
        "tc_msg21": [.turkish: "Cihazı Fabrika Ayarlarına Sıfırla", .english: "Restore the device to the factory settings", .german: "Gerät auf Werkseinstellungen zurücksetzen"],
        "tc_msg22": [.turkish: "Parlaklık", .english: "Brightness", .german: "Helligkeit"],
        "tc_msg23": [.turkish: "Hız", .english: "Speed", .german: "Geschwindigkeit"],
        "tc_msg24": [.turkish: "Renk", .english: "Color", .german: "Farbe"],
        "tc_msg25": [.turkish: "Renkli", .english: "Colourful", .german: "Mehrere Farben"],
        "tc_msg26": [.turkish: "Profil", .english: "Profile", .german: "Konfigurationsdatei"],
        "tc_msg27": [.turkish: "Profil", .english: "Profile", .german: "Konfiguration"],
        "tc_msg28": [.turkish: "Komutlar", .english: "Commands", .german: "Allgemeine Befehle"],
        "tc_msg29": [.turkish: "Klavye", .english: "Keyboard", .german: "Tastatur"],
        "tc_msg3": [.turkish: "Donanım Yazılımı Sürümü", .english: "Firmware version", .german: "Firmware-Version"],
        "tc_msg30": [.turkish: "Fare", .english: "Mouse", .german: "Maus"],
        "tc_msg31": [.turkish: "Medya", .english: "Multimedia", .german: "Multimedia"],
        "tc_msg32": [.turkish: "Tuş Kombinasyonu", .english: "Key combination", .german: "Kombinationstaste"],
        "tc_msg33": [.turkish: "Lütfen Tek Bir Tuş veya Tuş Kombinasyonu Girin", .english: "Please enter a single key or key combination", .german: "Bitte geben Sie eine einzelne Taste oder Tastenkombination ein"],
        "tc_msg34": [.turkish: "Kablosuz Modda, klavye belirtilen süre boyunca boşta kalırsa uyku moduna geçecektir", .english: "In wireless mode,keyboard will go into sleep after idle for a specified time", .german: "Im drahtlosen Modus wechselt das Gerät nach Ablauf der angegebenen Leerlaufzeit automatisch in den Ruhezustand"],
        "tc_msg35": [.turkish: "Lütfen Cihazınızı Bağlayın.", .english: "Please connect your device.", .german: "Gerät wird gesucht, bitte verbinden Sie Ihr Gerät"],
        "tc_msg36": [.turkish: "Saniye", .english: "Second", .german: "Sekunden"],
        "tc_msg37": [.turkish: "Dakika", .english: "Min", .german: "Minuten"],
        "tc_msg38": [.turkish: "ms (Milisaniye)", .english: "ms", .german: "Millisekunden"],
        "tc_msg39": [.turkish: "Yeniden Adlandır", .english: "Rename", .german: "Umbenennen"],
        "tc_msg4": [.turkish: "Yazılım Sürümü", .english: "Software version", .german: "Software-Version"],
        "tc_msg40": [.turkish: "İçe Aktar", .english: "Import", .german: "Importieren"],
        "tc_msg41": [.turkish: "Dışa Aktar", .english: "Export", .german: "Exportieren"],
        "tc_msg42": [.turkish: "Kopyala", .english: "Copy", .german: "Kopieren"],
        "tc_msg43": [.turkish: "Lütfen Bir Tuş Girin", .english: "Please enter a key", .german: "Bitte Taste eingeben"],
        "tc_msg44": [.turkish: "Cihaz Uyku Modunda veya Bağlantısı Kesildi", .english: "The device is asleep or disconnected", .german: "Gerät ist im Schlafmodus oder getrennt"],
        "tc_msg45": [.turkish: "Cihaz Bilgileri", .english: "Device Info", .german: "Geräteinformationen"],
        "tc_msg46": [.turkish: "Dil", .english: "Language", .german: "Sprache"],
        "tc_msg47": [.turkish: "Başlangıç", .english: "Startup", .german: "Startup"],
        "tc_msg48": [.turkish: "Çıkış", .english: "Exit", .german: "Beenden"],
        "tc_msg49": [.turkish: "Uyku", .english: "Sleep", .german: "Schlafmodus"],
        "tc_msg5": [.turkish: "Pil", .english: "Battery", .german: "Verbleibende Batterie"],
        "tc_msg50": [.turkish: "Sıfırlama", .english: "Reset", .german: "Aufwachen"],
        "tc_msg51": [.turkish: "Güncelleme", .english: "Upgrade", .german: "Aktualisieren"],
        "tc_msg52": [.turkish: "Lütfen Bekleyin.....", .english: "Please wait.....", .german: "Bitte warten, Daten werden aktualisiert....."],
        "tc_msg53": [.turkish: "Ayarlama Hatası, Cihaz Meşgul veya Kablosuz Parazit Var, Lütfen Daha Sonra Tekrar Deneyin", .english: "Setting error, device busy or wireless interference, please try again later", .german: "Fehler bei der Konfiguration, auf dem Gerät beschäftigt oder wireless-Interferenz, versuchen Sie es später erneut"],
        "tc_msg54": [.turkish: "Çakışma Önleme (Debounce)", .english: "Debounce", .german: "zu zittern."],
        "tc_msg55": [.turkish: "Aşama", .english: "Stage", .german: "Die Phase"],
        "tc_msg56": [.turkish: "Yeni", .english: "New", .german: "New"],
        "tc_msg57": [.turkish: "İptal Ediliyor", .english: "Canceling", .german: "Canceling"],
        "tc_msg58": [.turkish: "Cihaz Yavaş Yanıt Veriyor ve Kablosuz Parazit Olabilir. Lütfen Klavyeyi ve Alıcıyı Mümkün Olduğunca Yakın Tutun.", .english: "The device responds slowly and may have wireless interference. Please keep the keyboard and receiver as close as possible.", .german: "The device responds slowly and may have wireless interference. Please keep the keyboard and receiver as close as possible."],
        "tc_msg6": [.turkish: "X Düğmesine Tıkladığınızda", .english: "When you click the X button", .german: "Beim Klicken auf die X-Taste"],
        "tc_msg7": [.turkish: "Çıkış", .english: "Exit", .german: "Direkt beenden"],
        "tc_msg8": [.turkish: "Sistem Tepsi Bölgesinde Kalır", .english: "Resides in the system tray area", .german: "In die untere rechte Ecke minimieren"],
        "tc_msg9": [.turkish: "Cihaz", .english: "Device", .german: "Gerät"],
        "tc_music1": [.turkish: "Müzik", .english: "Music", .german: "Musik"],
        "tc_music10": [.turkish: "Otomatik Kazanç (Otomatik Ses Artışı)", .english: "Auto Gain", .german: "Automatischer Gewinn"],
        "tc_music2": [.turkish: "Kazanç (Ses Artışı)", .english: "Gain", .german: "Verstärkungsfaktor"],
        "tc_music3": [.turkish: "Klavye ışığı, sistem sesinin ritmine göre değişir", .english: "The keyboard light changes with the rhythm of the system sound", .german: "Die Tastaturbeleuchtung ändert sich entsprechend dem Rhythmus des Systemklangs"],
        "tc_music4": [.turkish: "Renk", .english: "Color", .german: "Einzelfarbe"],
        "tc_music5": [.turkish: "Renkli", .english: "ColorFull", .german: "Gemischte Farbe"],
        "tc_music6": [.turkish: "ACİK", .english: "ON", .german: "Ein"],
        "tc_music7": [.turkish: "KAPALI", .english: "OFF", .german: "Aus"],
        "tc_music8": [.turkish: "Efekt", .english: "Effect", .german: "Effekt"],
        "tc_music9": [.turkish: "Hafif (Düzgün)", .english: "Smooth", .german: "Weich"],
        "tc_music_mode1": [.turkish: "Ses Dansı - Yumuşak", .english: "Audio dance - soft", .german: "Audio-Tanz - Sanft"],
        "tc_music_mode10": [.turkish: "İpek Gibi Yağmur - Düzenli", .english: "Raining like silk - regular", .german: "Schnee fällt wie Seide - Regelmäßig"],
        "tc_music_mode2": [.turkish: "Parlak - Rock", .english: "Dazzling - rock", .german: "Blendend - Rock"],
        "tc_music_mode3": [.turkish: "Bulutlar Yükselir ve Kar Yağar - Normal", .english: "Clouds rise and snow fly - routine", .german: "Wolken steigen und Schnee fliegt - Routine"],
        "tc_music_mode4": [.turkish: "Işık Alanı Değişimi - Ses", .english: "Light Field Change - voice", .german: "Lichtfeldwechsel - Stimme"],
        "tc_music_mode5": [.turkish: "Çınlayan Akarsu - Düzenli", .english: "The gurgling stream - regular", .german: "Der klingende Bach - Regelmäßig"],
        "tc_music_mode6": [.turkish: "Çiçek Açma - Tutku", .english: "Blooming - passion", .german: "Blühen - Leidenschaft"],
        "tc_music_mode7": [.turkish: "İnci Jade Tabağa Düşüyor - Rock", .english: "Pearl falling jade plate - rock", .german: "Perlen fallen auf Jadeplatten - Rock"],
        "tc_music_mode8": [.turkish: "Bulutlar Ayı Takip Eder - Tutku", .english: "Clouds follow the moon - passion", .german: "Wolken folgen dem Mond - Leidenschaft"],
        "tc_music_mode9": [.turkish: "Dağlar ve Akışkan Su - Düzenli", .english: "Mountains and Flowing Waters - regular", .german: "Berge und fließendes Wasser - Regelmäßig"],
        "tc_mute": [.turkish: "Sessiz Mod", .english: "Mute", .german: "Stumm"],
        "tc_next_media": [.turkish: "Sonrak", .english: "Next", .german: "Nächster Titel"],
        "tc_ok": [.turkish: "Tamam", .english: "OK", .german: "Bestätigen"],
        "tc_player": [.turkish: "Çalar", .english: "Çalar", .german: "Çalar"],
        "tc_pre_media": [.turkish: "Öncek", .english: "Previous", .german: "Vorheriger Titel"],
        "tc_restore": [.turkish: "Sıfırlama", .english: "Reset", .german: "Standardeinstellungen wiederherstellen"],
        "tc_screen1": [.turkish: "Görüntünün görüntülenecek kısmını şeffaf alana yerleştirin", .english: "Görüntünün görüntülenecek kısmını şeffaf alana yerleştirin", .german: "Görüntünün görüntülenecek kısmını şeffaf alana yerleştirin"],
        "tc_screen10": [.turkish: "Geri Al", .english: "Geri Al", .german: "Geri Al"],
        "tc_screen11": [.turkish: "Ekran boyutu", .english: "Ekran boyutu", .german: "Ekran boyutu"],
        "tc_screen12": [.turkish: "Uygula", .english: "Uygula", .german: "Uygula"],
        "tc_screen13": [.turkish: "Maksimum kare sayısına ulaşıldı", .english: "Maksimum kare sayısına ulaşıldı", .german: "Maksimum kare sayısına ulaşıldı"],
        "tc_screen14": [.turkish: "Yeni", .english: "Yeni", .german: "Yeni"],
        "tc_screen15": [.turkish: "İçe Aktar", .english: "İçe Aktar", .german: "İçe Aktar"],
        "tc_screen16": [.turkish: "Oynatma aralığı（ms）", .english: "Oynatma aralığı（ms）", .german: "Oynatma aralığı（ms）"],
        "tc_screen17": [.turkish: "Lütfen önce oynatmayı duraklatın", .english: "Lütfen önce oynatmayı duraklatın", .german: "Lütfen önce oynatmayı duraklatın"],
        "tc_screen18": [.turkish: "kareler", .english: "kareler", .german: "kareler"],
        "tc_screen19": [.turkish: "Kablosuz bağlantı sırasında görüntü aktarımı desteklenmiyor, lütfen USB'ye bağlayın", .english: "Kablosuz bağlantı sırasında görüntü aktarımı desteklenmiyor, lütfen USB'ye bağlayın", .german: "Kablosuz bağlantı sırasında görüntü aktarımı desteklenmiyor, lütfen USB'ye bağlayın"],
        "tc_screen2": [.turkish: "Sol tıklayarak katmanı sürükleyin, kaydırma tekerleğiyle katmanı yakınlaştırın/uzaklaştırın", .english: "Sol tıklayarak katmanı sürükleyin, kaydırma tekerleğiyle katmanı yakınlaştırın/uzaklaştırın", .german: "Sol tıklayarak katmanı sürükleyin, kaydırma tekerleğiyle katmanı yakınlaştırın/uzaklaştırın"],
        "tc_screen20": [.turkish: "Sola döndür", .english: "Sola döndür", .german: "Sola döndür"],
        "tc_screen21": [.turkish: "Sağa döndür", .english: "Sağa döndür", .german: "Sağa döndür"],
        "tc_screen3": [.turkish: "Kare sayısı maksimum değeri aşıyor.", .english: "Kare sayısı maksimum değeri aşıyor.", .german: "Kare sayısı maksimum değeri aşıyor."],
        "tc_screen4": [.turkish: "Ekran ön izlemesi", .english: "Ekran ön izlemesi", .german: "Ekran ön izlemesi"],
        "tc_screen5": [.turkish: "Kare Listesi", .english: "Kare Listesi", .german: "Kare Listesi"],
        "tc_screen6": [.turkish: "Tüm karelere uygula", .english: "Tüm karelere uygula", .german: "Tüm karelere uygula"],
        "tc_screen7": [.turkish: "Yükle", .english: "Yükle", .german: "Yükle"],
        "tc_screen8": [.turkish: "Katman Ekle", .english: "Katman Ekle", .german: "Katman Ekle"],
        "tc_screen9": [.turkish: "Kaydet", .english: "Kaydet", .german: "Kaydet"],
        "tc_scrolldown": [.turkish: "Aşağı Kaydır", .english: "Scroll Down", .german: "Nach unten scrollen"],
        "tc_scrollup": [.turkish: "Yukarı Kaydır", .english: "Scroll Up", .german: "Nach oben scrollen"],
        "tc_stop": [.turkish: "Durdur", .english: "Stop", .german: "Wiedergabe stoppen"],
        "tc_update1": [.turkish: "Yeni Donanım Yazılımı Algılandı. Güncellemek İster Misiniz? (Güncellemeden Sonra Klavyeyi Tekrar Takın)", .english: "Detect a New Firmware. Do You Want to Upgrade It? (Please Re-Plug the Keyboard after Upgrading)", .german: "Detect a New Firmware. Do You Want to Upgrade It? (Please Re-Plug the Keyboard after Upgrading)"],
        "tc_update2": [.turkish: "Yeni bir sürücü sürümü algılandı. Şimdi güncellemek ister misiniz？", .english: "A new version of driver is detected. Do you want to update it now？", .german: "A new version of driver is detected. Do you want to update it now？"],
        "tc_update3": [.turkish: "Yazılım şu anda en son sürümdür.", .english: "The software is currently the latest version.", .german: "The software is currently the latest version."],
        "tc_update4": [.turkish: "İndiriliyor", .english: "Downloading", .german: "Downloading"],
        "tc_update5": [.turkish: "Güncelleme Hatası", .english: "Update error", .german: "Update error"],
        "tc_update6": [.turkish: "Donanım Yazılımı Güncelleme", .english: "Firmware Update", .german: "Firmware Update"],
        "tc_update7": [.turkish: "Sürücü Güncelleme", .english: "Driver Update", .german: "Driver Update"],
        "tc_update8": [.turkish: "Lütfen önce cihazı USB bağlantısına geçirin", .english: "Please switch the device to USB connection first", .german: "Please switch the device to USB connection first"],
        "tc_vol_dw": [.turkish: "Ses -", .english: "Volume -", .german: "Lautstärke -"],
        "tc_vol_up": [.turkish: "Ses +", .english: "Volume +", .german: "Lautstärke +"],
        "tc_web": [.turkish: "https://dekaythailand.com/", .english: "https://dekaythailand.com/", .german: "https://dekaythailand.com/"],
        "tc_yun1": [.turkish: "Sharing Center", .english: "Sharing Center", .german: "Sharing Center"],
        "tc_yun10": [.turkish: "What games or software can this macro be used on", .english: "What games or software can this macro be used on", .german: "What games or software can this macro be used on"],
        "tc_yun11": [.turkish: "Download succeeded. Do you want to view it now？", .english: "Download succeeded. Do you want to view it now？", .german: "Download succeeded. Do you want to view it now？"],
        "tc_yun12": [.turkish: "Please login", .english: "Please login", .german: "Please login"],
        "tc_yun13": [.turkish: "Login", .english: "Login", .german: "Login"],
        "tc_yun14": [.turkish: "Log out", .english: "Log out", .german: "Log out"],
        "tc_yun15": [.turkish: "Register", .english: "Register", .german: "Register"],
        "tc_yun16": [.turkish: "User name", .english: "User name", .german: "User name"],
        "tc_yun17": [.turkish: "Password", .english: "Password", .german: "Password"],
        "tc_yun18": [.turkish: "Confirm password", .english: "Confirm password", .german: "Confirm password"],
        "tc_yun19": [.turkish: "Email", .english: "Email", .german: "Email"],
        "tc_yun2": [.turkish: "Name", .english: "Name", .german: "Name"],
        "tc_yun20": [.turkish: "Sex", .english: "Sex", .german: "Sex"],
        "tc_yun21": [.turkish: "Male", .english: "Male", .german: "Male"],
        "tc_yun22": [.turkish: "Female", .english: "Female", .german: "Female"],
        "tc_yun23": [.turkish: "The name is already registered", .english: "The name is already registered", .german: "The name is already registered"],
        "tc_yun24": [.turkish: "The email has been registered", .english: "The email has been registered", .german: "The email has been registered"],
        "tc_yun25": [.turkish: "Please enter the correct email", .english: "Please enter the correct email", .german: "Please enter the correct email"],
        "tc_yun26": [.turkish: "The passwords entered twice are inconsistent", .english: "The passwords entered twice are inconsistent", .german: "The passwords entered twice are inconsistent"],
        "tc_yun27": [.turkish: "Please keep the password length between 6 and 20 characters", .english: "Please keep the password length between 6 and 20 characters", .german: "Please keep the password length between 6 and 20 characters"],
        "tc_yun28": [.turkish: "Server not responding or network connection error", .english: "Server not responding or network connection error", .german: "Server not responding or network connection error"],
        "tc_yun29": [.turkish: "Incorrect username or password", .english: "Incorrect username or password", .german: "Incorrect username or password"],
        "tc_yun3": [.turkish: "Description", .english: "Description", .german: "Description"],
        "tc_yun30": [.turkish: "Register successful", .english: "Register successful", .german: "Register successful"],
        "tc_yun31": [.turkish: "No account yet. Register now", .english: "No account yet. Register now", .german: "No account yet. Register now"],
        "tc_yun32": [.turkish: "Automatic logon", .english: "Automatic logon", .german: "Automatic logon"],
        "tc_yun33": [.turkish: "Upload to cloud", .english: "Upload to cloud", .german: "Upload to cloud"],
        "tc_yun34": [.turkish: "Submitted successfully", .english: "Submitted successfully", .german: "Submitted successfully"],
        "tc_yun35": [.turkish: "My cloud profile", .english: "My cloud profile", .german: "My cloud profile"],
        "tc_yun36": [.turkish: "Device", .english: "Device", .german: "Device"],
        "tc_yun37": [.turkish: "Personal panel", .english: "Personal panel", .german: "Personal panel"],
        "tc_yun38": [.turkish: "There is already a profile with the same name. Do you want to overwrite it？", .english: "There is already a profile with the same name. Do you want to overwrite it？", .german: "There is already a profile with the same name. Do you want to overwrite it？"],
        "tc_yun39": [.turkish: "Suggestions and feedback", .english: "Suggestions and feedback", .german: "Suggestions and feedback"],
        "tc_yun4": [.turkish: "Software", .english: "Software", .german: "Software"],
        "tc_yun40": [.turkish: "Your contact information", .english: "Your contact information", .german: "Your contact information"],
        "tc_yun41": [.turkish: "Submit", .english: "Submit", .german: "Submit"],
        "tc_yun42": [.turkish: "Change Password", .english: "Change Password", .german: "Change Password"],
        "tc_yun43": [.turkish: "Original password", .english: "Original password", .german: "Original password"],
        "tc_yun44": [.turkish: "New password", .english: "New password", .german: "New password"],
        "tc_yun45": [.turkish: "Confirm password", .english: "Confirm password", .german: "Confirm password"],
        "tc_yun46": [.turkish: "The password is changed", .english: "The password is changed", .german: "The password is changed"],
        "tc_yun47": [.turkish: "This profile is not applicable to the current device", .english: "This profile is not applicable to the current device", .german: "This profile is not applicable to the current device"],
        "tc_yun5": [.turkish: "User", .english: "User", .german: "User"],
        "tc_yun6": [.turkish: "Date", .english: "Date", .german: "Date"],
        "tc_yun7": [.turkish: "Download", .english: "Download", .german: "Download"],
        "tc_yun8": [.turkish: "Share", .english: "Share", .german: "Share"],
        "tc_yun9": [.turkish: "Describe the function of the macro or precautions for use", .english: "Describe the function of the macro or precautions for use", .german: "Describe the function of the macro or precautions for use"],
    ]
    
    func tr(_ key: String, default defaultVal: String? = nil) -> String {
        if let dict = translations[key], let val = dict[currentLanguage], !val.isEmpty {
            return val
        }
        return defaultVal ?? key
    }
    
    func setLanguage(_ lang: AppLanguage) {
        withAnimation(.easeInOut(duration: 0.2)) {
            currentLanguage = lang
        }
    }
}
